version: '3'
services:
  magento:
    build:
      context: 'magento'
      args:
        - 'USER_ID=${USER_ID}'
        - 'GROUP_ID=${GROUP_ID}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'XDEBUG=${XDEBUG}'
        - 'INSTALL_ADDITIONAL_EXTENSIONS=${INSTALL_ADDITIONAL_EXTENSIONS}'
        - 'DB_NAME=${DB_NAME}'
        - 'DB_USER=${DB_USER}'
        - 'DB_PASSWORD=${DB_PASSWORD}'
        - 'ADMIN_PASSWD=${ADMIN_PASSWD}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_MAGENTO}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${MAGENTO_HOST_HTTP_PORT}:80'
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - '${MYSQL_PORT}:3306'
  elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
        environment:
          - node.name=elasticsearch
          - cluster.name=es-docker-cluster
          - discovery.type=single-node
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - magento-es-data:/usr/share/elasticsearch/data
        ports:
          - '9200:9200'
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - 'PMA_ARBITRARY=1'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    ports:
      - '${PMA_PORT}:80'
volumes:
  magento-es-data: